package:
  name: malmo
  version: 0.35.6.0

source:
  git_url: https://github.com/Microsoft/malmo.git
  git_rev: 0.35.6

build:
  number: 1

requirements:
  build:
    - python {{ python }}
    - cmake 3.11.1
    - boost 1.67
    - ffmpeg
    - openjdk 8.*
    - mono # [not win64]
    - doxygen
    - curl
    - toolchain # [linux and not py36]
    - vs2015_runtime # [win]
    - zlib # [win]

    - unxutils # [win]
    - gcc # [linux and py36]
    - pthread-stubs # [linux]
    - swig # [linux]
    - swig # [win64]
    - icu # [linux]
    - make
  run:
    - python {{ python }}
    - boost 1.67
    - ffmpeg
    - openjdk 8.*
    - mono # [not win64]
    - curl
    - toolchain # [linux and not py36]
    - zlib # [win]


    - vs2015_runtime # [win]
    - swig # [win64]
    - gcc # [linux and py36] 
    - pthread-stubs # [linux]
    - swig # [linux]
    - icu # [linux]

about:
  home: https://www.microsoft.com/en-us/research/project/project-malmo/
  license: "MIT License"
  summary: "Conda package for Project Malmo, a platform for Artificial Intelligence experimentation and research built on top of Minecraft"
  author: "S.P. Mohanty"
  email: "sharada.mohanty@epfl.ch"
