package:
  name: malmo
  version: 0.36.0

source:
  git_url: https://github.com/Microsoft/malmo.git
  git_rev: 0.36.0
  patches:
    - 0001-Don-t-link-to-libpythonXY.dll-so-dylib.patch
    - 0002-Make-BOOST_PYTHON_MODULE_NAME-configurable-on-all-pl.patch
    - 0003-Drop-zlib-not-necessarily-a-boost-component-Turn-off.patch
    - 0004-Set-Boost_USE_STATIC_LIBS-before-find_package.patch

build:
  number: 0
  ignore_run_exports:
    # Gonna link it statically (symbols may still be exposed, but less risky
    # than mixing defaults and conda-forge)
    - boost

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - swig
  host:
    - python
    - setuptools
    - boost
    - zlib
    - openjdk
  run:
    - python
    - {{ pin_compatible('openjdk', max_pin='x') }}

test:
  imports:         # [unix]
    - MalmoPython  # [unix]
  commands:
    - python -c "from malmo import MalmoPython"

about:
  home: https://www.microsoft.com/en-us/research/project/project-malmo
  dev_url: https://github.com/Microsoft/malmo
  license: "MIT License"
  summary: "Conda package for Project Malmo, a platform for Artificial Intelligence experimentation and research built on top of Minecraft"
  author: "S.P. Mohanty"
  email: "sharada.mohanty@epfl.ch"
