package:
  name: malmo
  version: 0.31.0.0

source:
  git_url: https://github.com/Microsoft/malmo.git
  git_rev: 0.31.0


build:
  number: 1

requirements:
  build:
    - python {{ python }}
    - cmake
    - boost 1.66
    - ffmpeg
    - openjdk 8.*
    - xerces-c 3.2.*
    - mono
    - doxygen
    - xsd-marlo
    - curl
    - gcc # [linux]
    - pthread-stubs # [linux]
    - swig # [linux]
    - icu # [linux]
  run:
    - python {{ python }}
    - boost 1.66
    - ffmpeg
    - openjdk 8.*
    - xerces-c 3.2.*
    - mono
    - xsd-marlo
    - curl
    - gcc # [linux]
    - pthread-stubs # [linux]
    - swig # [linux]
    - icu # [linux]

about:
  home: https://www.microsoft.com/en-us/research/project/project-malmo/
  license: "MIT License"
  summary: "Conda package for Project Malmo, a platform for Artificial Intelligence experimentation and research built on top of Minecraft"
  author: "S.P. Mohanty"
  email: "sharada.mohanty@epfl.ch"
